name: Build and Tests
on:
  push:
  pull_request:

jobs:
  checkout_build:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pantheon-public/php-ci:v7.4
    name: Checkout & Lint
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Save repo content as artifact
        uses: actions/upload-artifact@v3
        with:
          name: full-workspace
          path: ${{ github.workspace }}
      - name: Full Composer Install
        run: composer install
      - name: Validate Code
        run: composer lint
      - name: Coding Standards
        run: composer cs
  phpcompatibility:
    runs-on: ubuntu-latest
    name: PHP Compatibility
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PHPCompatibility
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: 7.4-8.3
          paths: ${{ github.workspace }}/src
  functional:
    runs-on: ${{ matrix.operating-system }}
    name: Functional testing matrix - PHP ${{ matrix.php-versions.value }} on ${{ matrix.operating-system }}
    if: ${{ github.repository_owner == 'pantheon-systems' }}
    strategy:
      matrix:
        operating-system: [ 'macos-latest' ]
        php-versions:
          - name: 74
            value: 7.4
          - name: 81
            value: 8.1
      max-parallel: 3
    env:
      TERMINUS_ALLOW_UNSUPPORTED_NEWER_PHP: true
      TERMINUS_VERSION: 3.1.1
      TERMINUS_SITE_NAME: test-icr-${{ github.run_id }}-${{ matrix.php-versions.name }}
    needs:
      - checkout_build
      - phpcompatibility
    steps:
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions.value }}
          extensions: gd, mbstring, zip, ssh2-1.3.1, pcov
          coverage: pcov
          ini-values: error_reporting=E_ALL
      - name: Install Terminus
        uses: pantheon-systems/terminus-github-actions@main
        with:
          pantheon-machine-token: ${{ secrets.TERMINUS_TOKEN }}
      - name: Download repo content from artifact
        uses: actions/download-artifact@v3
        with:
          name: full-workspace
      - name: Full Composer Install
        run: composer install
      - name: Run tests
        run: composer unit
      - name: Install plugin
        run: terminus self:plugin:install .
      - name: Run functional tests
        env:
          ORG_ID: ${{ secrets.ORG_ID }}
        run: chmod +x ./tests/functional.sh && ./tests/functional.sh
      - name: Cleanup
        if: always()
        run: terminus site:delete -y ${{ env.TERMINUS_SITE_NAME }}
